### ISSUE TITLE
Wrong bottom border

### ISSUE THREAD

**Issue by cristianbravolillo** [travail/php-Text-SimpleTable#2]
The bottom border is wrong. To fix it, you need to replace line 230 of SimpleTable.php from:

 $text = self::BOTTOM_SEPARATOR;

to

 $text .= self::BOTTOM_SEPARATOR;

**Comment by travail** [comment]
Thanks, will fix it.

**Comment by travail** [comment]
Fixed and publish the new release [v0.1.2](https://github.com/travail/php-Text-SimpleTable/releases/tag/v0.1.2).

**Comment by cristianbravolillo** [comment]
Thanks!
